# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ZZZBotris.Net CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
          
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Dependencies
      run: dotnet restore
    - name: Publish
      run: |
        mkdir ./pub
        dotnet publish -o ./pub
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: ZZZBotris
        path: ./pub
